Feature/4 apply tailwind theme system to appwide
zxcvbnmmohd/DeenUp pull request #8
Opened 2024-03-10 20:17 UTC by mjeylanii

2024-03-10 21:09 UTC, zxcvbnmmohd commented on .gitignore
> -expo-env.d.ts
why'd ya remove this?

2024-03-10 21:17 UTC, zxcvbnmmohd requested changes

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/app/friends-mode.tsx
> +			<View className="flex-col items-center gap-3">
don't forget to apply the same styling as above 
const styles = {
...
}

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/app/index.tsx
> +								className={styles.logo + " " + "text-primary"}
try to apply the way too avoid adding  in the class name, just mane a new option, it's calm

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/app/result/index.tsx
> +		bottomBtnsContainer: "flex h-14 flex-row gap-3 px-12",
don't abbreviate words

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/app/result/index.tsx
> +		animationContainerBg: "absolute top-40 size-96 rounded-3xl bg-primary",
here too

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/app/result/index.tsx
> +				<View className={"flex h-14 flex-row gap-3 px-12"}>
forgot to update this one

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/components/Button.tsx
> +	className?: string
put optional properties below required ones

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/components/Button.tsx
> +	const buttonVariant = tv({
this really cooooool ngl

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/components/Button.tsx
> +	const textStyle = textVariant({ size: props.size, color: props.color })
can you do a convert these to variants? lke
`const styles = {
text: textVariant({...}),
button:  buttonVariant({...}), etc...
}`

2024-03-10 21:17 UTC, zxcvbnmmohd commented on apps/expo/src/components/gameplay/QuestionHeader.tsx
>  	const { theme } = useTheme()
we still using this?

2024-03-10 21:33 UTC, mjeylanii commented on .gitignore
> -expo-env.d.ts
I didn't touch that

2024-03-11 12:34 UTC, zxcvbnmmohd approved these changes

2024-03-11 12:36 UTC, merged